--buat bikin user
alter session set "_ORACLE_SCRIPT"=true;
   
CREATE USER ahmgawpm IDENTIFIED BY miniproject;
GRANT ALL privileges TO ahmgawpm;

--bikin table 
CREATE TABLE HEADER_IKP
    (IKP_ID VARCHAR2(50 BYTE) PRIMARY KEY, 
	KAT_PEKERJAAN VARCHAR2(50 BYTE), 
	KAT_IZIN_KERJA VARCHAR2(50 BYTE), 
	TIPE_ORDER VARCHAR2(50 BYTE), 
	NO_PO VARCHAR2(50 BYTE), 
	NO_SPK VARCHAR2(50 BYTE), 
	DESKRIPSI_ITEM VARCHAR2(500 BYTE), 
	PLANT_ID VARCHAR2(4 BYTE), 
	NO_PENGAJUAN_PROYEK VARCHAR2(50 BYTE), 
	PROJECT_DETAIL VARCHAR2(50 BYTE),
	START_JOB DATE,
	END_JOB DATE,
	PURCHASING_ORG VARCHAR2(50 BYTE), 
	NRP_ID NUMBER(22,0), 
	SUPPLY_ID VARCHAR2(50 BYTE), 
	SUPPLY_DESC VARCHAR2(500 BYTE), 
	NAMA_PENGAWAS VARCHAR2(50 BYTE), 
	HP_PENGAWAS VARCHAR2(50 BYTE), 
	NAMA_LK3 VARCHAR2(50 BYTE), 
	HP_LK3 VARCHAR2(50 BYTE),
	STATUS VARCHAR(50 BYTE),
	REMARK VARCHAR2(500)) ;

CREATE TABLE AREA_PEKERJAAN
   (	
	IKP_ID VARCHAR2(50 BYTE), 
	AREA_DETAIL VARCHAR2(50 BYTE), 
	IN_OUT VARCHAR2(50 BYTE), 
	CRITICALITY VARCHAR2(50 BYTE), 
	TASK_LIST VARCHAR2(50 BYTE), 
	LOGIN_PATROL VARCHAR2(50 BYTE), 
	ASSET_NO VARCHAR2(50),
	CONSTRAINT AREA_PEKERJAAN_PK PRIMARY KEY (VIKPID,VASSETNO)
	);

--2 PK "VIKPID" VASSETNO 



--LoV Supplier -- > Tabel Supplier
 CREATE TABLE SUPPLIER
 (	SUPPLY_ID VARCHAR2(50 BYTE) PRIMARY KEY, 
	SUPPLY_DESC VARCHAR2(50 BYTE) 
  ) ;


--LoV PO -- > Tabel PO
 CREATE TABLE PURCHASING_ORDER
 (	NO_PO VARCHAR2(50 BYTE)  PRIMARY KEY, 
	PO_DESC VARCHAR2(50 BYTE), 
	SUPPLY_ID VARCHAR2(50 BYTE),
    CONSTRAINT PURCHASING_ORDER_FK FOREIGN KEY (SUPPLY_ID) 
    REFERENCES SUPPLIER (SUPPLY_ID)
  ) ;
--nyambung ke Supplier lewat "SUPPLY_ID" 

--LoV PIC -- > Tabel PIC
 CREATE TABLE PIC
 (	NRP_ID VARCHAR2(50 BYTE) PRIMARY KEY, 
	NAMA VARCHAR2(50 BYTE), 
        DEPARTEMEN VARCHAR2(50 BYTE), 
	SEKSI VARCHAR2(50 BYTE), 
	DIVISI VARCHAR2(50 BYTE)
  ) ;

--LoV Plant -- > Tabel Plant
 CREATE TABLE PLANT
 (	PLANT_VAR VARCHAR2(50 BYTE) PRIMARY KEY, 
	PLANT_DESC VARCHAR2(50 BYTE)
  ) ;

--LoV Asset -- > Tabel Asset
 CREATE TABLE ASSET
 (	NO_ASSET VARCHAR2(50 BYTE)  PRIMARY KEY, 
	DESC_ASSET VARCHAR2(50 BYTE), 
	PLANT_VAR VARCHAR2(50 BYTE), 
	CONSTRAINT ASSET_FK FOREIGN KEY (PLANT_VAR )
	REFERENCES PLANT(PLANT_VAR )
  ) ;
--nyambung ke plant lewat "PLANT_VAR " 

--LoV TaskList -- > Tabel TaskList
 CREATE TABLE TASK_LIST
 (	KODE_TASK_LIST VARCHAR2(50 BYTE) PRIMARY KEY , 
	TITLE_TASK_LIST VARCHAR2(50 BYTE), 
	NO_ASSET VARCHAR2(50 BYTE) ,
	CONSTRAINT TASK_LIST_FK FOREIGN KEY (NO_ASSET)
	REFERENCES ASSET(NO_ASSET)
	);
--nyambung ke asset lewat "NO_ASSET" 

CREATE TABLE USER
(USERNAME VARCHAR2(50 BYTE) PRIMARY KEY,
PASSWORD VARCHAR2(50 BYTE),
ROLE_NAME VARCHAR2(50 BYTE));


SELECT SUPPLY_ID, SUPPLY_DESC FROM HEADER_IKP
WHERE (:supplyId IS NULL OR SUPPLY_ID LIKE (CONCAT(CONCAT('%',:supplyId),'%')))
AND (:supplyDesc IS NULL OR SUPPLY_DESC LIKE (CONCAT(CONCAT('%', :supplyDesc), '%')));

SELECT NRP_ID, NAMA FROM PIC WHERE (:nrpId IS NULL OR NRP_ID LIKE (CONCAT(CONCAT('%',:nrpId),'%')))
AND (:nama IS NULL OR NAMA LIKE (CONCAT(CONCAT('%',:nama),'%')));

SELECT  count(*) FROM (SELECT NO_PO, PO_DESC FROM PURCHASING_ORDER WHERE (:noPo IS NULL OR NO_PO LIKE (CONCAT(CONCAT('%',:noPo),'%')))
AND (:poDesc IS NULL OR PO_DESC LIKE (CONCAT(CONCAT('%',:poDesc),'%')))) ;

SELECT PLANT_VAR, PLANT_DESC FROM PLANT WHERE (:plantVar IS NULL OR PLANT_VAR LIKE (CONCAT(CONCAT('%',:plantVar),'%')))
AND (:plantDesc IS NULL OR PLANT_DESC LIKE (CONCAT(CONCAT('%',:plantDesc),'%')));

SELECT NO_ASSET, DESC_ASSET FROM ASSET WHERE (:plantVar = PLANT_VAR)
AND (:noAsset IS NULL OR NO_ASSET LIKE (CONCAT(CONCAT('%',:noAsset),'%')))
AND (:descAsset IS NULL OR DESC_ASSET LIKE (CONCAT(CONCAT('%',:descAsset),'%')));

SELECT KODE_TASK_LIST, TITLE_TASK_LIST FROM TASK_LIST
WHERE (NO_ASSET = :noAsset)
AND (:kode IS NULL OR LOWER(KODE_TASK_LIST) LIKE LOWER(CONCAT(CONCAT('%',:kode),'%')))
AND (:title IS NULL OR LOWER(TITLE_TASK_LIST) LIKE LOWER(CONCAT(CONCAT('%',:title),'%')));

SELECT IKP_ID, PROJECT_DETAIL FROM HEADER_IKP WHERE (:ikpId IS NULL OR LOWER(IKP_ID) LIKE LOWER(CONCAT(CONCAT('%',:ikpId),'%')))
OR (:projectDetail IS NULL OR LOWER(PROJECT_DETAIL) LIKE LOWER(CONCAT(CONCAT('%',:projectDetail),'%')));

SELECT IKP_ID, ASSET_NO, AREA_DETAIL, IN_OUT, CRITICALITY, TASK_LIST FROM AREA_PEKERJAAN 
WHERE IKP_ID = :ikpId;

INSERT INTO "USER"  VALUES ('dararyanti','dararyanti','admin');