--buat bikin user
alter session set "_ORACLE_SCRIPT"=true;
   
CREATE USER ahmgawpm IDENTIFIED BY miniproject;
GRANT ALL privileges TO ahmgawpm;


--bikin table 
CREATE TABLE AHMGAWPM_HDRIKPS
    (VIKPID VARCHAR2(50 BYTE) PRIMARY KEY, 
	VWOCTGR VARCHAR2(50 BYTE), 
	VWOPERMIT VARCHAR2(50 BYTE), 
	VORDERTYPE VARCHAR2(50 BYTE), 
	VODRTYPNUM VARCHAR2(50 BYTE), 
	VNOSPK VARCHAR2(50 BYTE), 
	VITEMDESC VARCHAR2(500 BYTE), 
	VPLANTID VARCHAR2(4 BYTE), 
	VPROJSUB VARCHAR2(50 BYTE), 
	VPROJDTL VARCHAR2(50 BYTE),
	DSTARTJOB DATE,
	DENDJOB DATE,
	VPURCHORG VARCHAR2(50 BYTE), 
	VPICNRPID NUMBER(22,0), 
	VSUPPLYID VARCHAR2(50 BYTE), 
	VSUPPLDESC VARCHAR2(500 BYTE), 
	VNAME VARCHAR2(50 BYTE), 
	VHP VARCHAR2(50 BYTE), 
	VNAMELK3 VARCHAR2(50 BYTE), 
	VHPLK3 VARCHAR2(50 BYTE),
	VSTATUS VARCHAR(50 BYTE),
	VCREA VARCHAR2(20 BYTE), 
	DCREA DATE, 
	VMODI VARCHAR2(20 BYTE), 
	DMODI DATE,
	VREMARK VARCHAR2(500)) ;

CREATE TABLE AHMGAWPM_DTLIKPAREAS 
   (	
	VIKPID VARCHAR2(50 BYTE), 
	VAREADTL VARCHAR2(50 BYTE), 
	VINOUT VARCHAR2(50 BYTE), 
	VCRIT VARCHAR2(50 BYTE), 
	VTASKLIST VARCHAR2(50 BYTE), 
	VLGINPATROL VARCHAR2(50 BYTE), 
	VASSETNO VARCHAR2(50),
	CONSTRAINT AHMGAWPM_DTLIKPAREAS_PK PRIMARY KEY (VIKPID,VASSETNO)
	);

--2 PK "VIKPID" VASSETNO 



--LoV Supplier -- > Tabel Supplier
 CREATE TABLE AHMGAWPM_TBLSUPPLIER 
 (	VSUPPLYID VARCHAR2(50 BYTE) PRIMARY KEY, 
	VSUPPLDESC VARCHAR2(50 BYTE) 
  ) ;


--LoV PO -- > Tabel PO
 CREATE TABLE AHMGAWPM_TBLPO
 (	VNOPO VARCHAR2(50 BYTE)  PRIMARY KEY, 
	VPODESC VARCHAR2(50 BYTE), 
	VSUPPLYID VARCHAR2(50 BYTE),
    CONSTRAINT AHMGAWPM_TBLPO_FK FOREIGN KEY (VSUPPLYID) 
    REFERENCES AHMGAWPM_TBLSUPPLIER (VSUPPLYID)
  ) ;
--nyambung ke Supplier lewat "VSUPPLYID" 


--LoV PIC -- > Tabel PIC
 CREATE TABLE AHMGAWPM_TBLPIC
 (	VNRP VARCHAR2(50 BYTE) PRIMARY KEY, 
	VNAMA VARCHAR2(50 BYTE), 
        VNAMADEPTHEAD VARCHAR2(50 BYTE), 
	VNAMASEKSI VARCHAR2(50 BYTE), 
	VNAMADIVISI VARCHAR2(50 BYTE)
  ) ;

--LoV Plant -- > Tabel Plant
 CREATE TABLE AHMGAWPM_TBLPLANT
 (	VPLANTVAR VARCHAR2(50 BYTE) PRIMARY KEY, 
	VPLANTDESC VARCHAR2(50 BYTE)
  ) ;

--LoV Asset -- > Tabel Asset
 CREATE TABLE AHMGAWPM_TBLASSET
 (	VNOASSET VARCHAR2(50 BYTE)  PRIMARY KEY, 
	VDESCASSET VARCHAR2(50 BYTE), 
	VPLANTVAR VARCHAR2(50 BYTE), 
	CONSTRAINT AHMGAWPM_TBLASSET_FK FOREIGN KEY (VPLANTVAR)
	REFERENCES AHMGAWPM_TBLPLANT(VPLANTVAR)
  ) ;
--nyambung ke plant lewat "VPLANTVAR" 

--LoV TaskList -- > Tabel TaskList
 CREATE TABLE AHMGAWPM_TBLTASKLIST
 (	VKODETASKLIST VARCHAR2(50 BYTE) PRIMARY KEY , 
	VTITLETASKLIST VARCHAR2(50 BYTE), 
	VNOASSET VARCHAR2(50 BYTE) ,
	CONSTRAINT AHMGAWPM_TBLTASKLIST_FK FOREIGN KEY (VNOASSET)
	REFERENCES AHMGAWPM_TBLASSET(VNOASSET)
	);
--nyambung ke asset lewat "VNOASSET" 

CREATE TABLE AHMGAWPM_TBLUSER
(USERNAME VARCHAR2(50 BYTE) PRIMARY KEY,
PASSWORD VARCHAR2(50 BYTE),
ROLE_NAME VARCHAR2(50 BYTE));

--TABEL AREA
ALTER TABLE AHMGAWPM.AREA_PEKERJAAN RENAME COLUMN VIKPID TO IKP_ID;
ALTER TABLE AHMGAWPM.AREA_PEKERJAAN RENAME COLUMN VAREADTL TO AREA_DETAIL;
ALTER TABLE AHMGAWPM.AREA_PEKERJAAN RENAME COLUMN VINOUT TO IN_OUT;
ALTER TABLE AHMGAWPM.AREA_PEKERJAAN RENAME COLUMN VCRIT TO CRITICALITY;
ALTER TABLE AHMGAWPM.AREA_PEKERJAAN RENAME COLUMN VTASKLIST TO TASK_LIST;
ALTER TABLE AHMGAWPM.AREA_PEKERJAAN RENAME COLUMN VLGINPATROL TO LOGIN_PATROL;
ALTER TABLE AHMGAWPM.AREA_PEKERJAAN RENAME COLUMN VASSETNO TO ASSET_NO;
ALTER TABLE AHMGAWPM.AHMGAWPM_DTLIKPAREAS RENAME TO AREA_PEKERJAAN;

--TABEL HEADER IKP
ALTER TABLE AHMGAWPM.AHMGAWPM_HDRIKPS RENAME TO HEADER_IKP;
ALTER TABLE AHMGAWPM.HEADER_IKP RENAME COLUMN VIKPID TO IKP_ID;
ALTER TABLE AHMGAWPM.HEADER_IKP RENAME COLUMN VWOCTGR TO KAT_PEKERJAAN;
ALTER TABLE AHMGAWPM.HEADER_IKP RENAME COLUMN VWOPERMIT TO KAT_IZIN_KERJA;
ALTER TABLE AHMGAWPM.HEADER_IKP RENAME COLUMN VORDERTYPE TO TIPE_ORDER;
ALTER TABLE AHMGAWPM.HEADER_IKP RENAME COLUMN VODRTYPNUM TO NO_PO;
ALTER TABLE AHMGAWPM.HEADER_IKP RENAME COLUMN VNOSPK TO NO_SPK;
ALTER TABLE AHMGAWPM.HEADER_IKP RENAME COLUMN VITEMDESC TO DESKRIPSI_ITEM;
ALTER TABLE AHMGAWPM.HEADER_IKP RENAME COLUMN VPLANTID TO PLANT_ID;
ALTER TABLE AHMGAWPM.HEADER_IKP RENAME COLUMN VPROJSUB TO NO_PENGAJUAN_PROYEK;
ALTER TABLE AHMGAWPM.HEADER_IKP RENAME COLUMN VPROJDTL TO PROJECT_DETAIL;
ALTER TABLE AHMGAWPM.HEADER_IKP RENAME COLUMN DSTARTJOB TO START_JOB;
ALTER TABLE AHMGAWPM.HEADER_IKP RENAME COLUMN DENDJOB TO END_JOB;
ALTER TABLE AHMGAWPM.HEADER_IKP RENAME COLUMN VPURCHORG TO PURCHASING_ORG;
ALTER TABLE AHMGAWPM.HEADER_IKP RENAME COLUMN VPICNRPID TO NRP_ID;
ALTER TABLE AHMGAWPM.HEADER_IKP RENAME COLUMN VSUPPLYID TO SUPPLY_ID;
ALTER TABLE AHMGAWPM.HEADER_IKP RENAME COLUMN VSUPPLDESC TO SUPPLY_DESC;
ALTER TABLE AHMGAWPM.HEADER_IKP RENAME COLUMN VNAME TO NAMA_PENGAWAS;
ALTER TABLE AHMGAWPM.HEADER_IKP RENAME COLUMN VHP TO HP_PENGAWAS;
ALTER TABLE AHMGAWPM.HEADER_IKP RENAME COLUMN VNAMELK3 TO NAMA_LK3;
ALTER TABLE AHMGAWPM.HEADER_IKP RENAME COLUMN VHPLK3 TO HP_LK3;
ALTER TABLE AHMGAWPM.HEADER_IKP RENAME COLUMN VSTATUS TO STATUS;
ALTER TABLE AHMGAWPM.HEADER_IKP RENAME COLUMN VREMARK TO REMARK;
ALTER TABLE AHMGAWPM.HEADER_IKP DROP COLUMN VCREA;
ALTER TABLE AHMGAWPM.HEADER_IKP DROP COLUMN DCREA;
ALTER TABLE AHMGAWPM.HEADER_IKP DROP COLUMN VMODI;
ALTER TABLE AHMGAWPM.HEADER_IKP DROP COLUMN DMODI;

--TABEL ASSET
ALTER TABLE AHMGAWPM.AHMGAWPM_TBLASSET RENAME TO ASSET;
ALTER TABLE AHMGAWPM.ASSET RENAME COLUMN VNOASSET TO NO_ASSET;
ALTER TABLE AHMGAWPM.ASSET RENAME COLUMN VDESCASSET TO DESC_ASSET;
ALTER TABLE AHMGAWPM.ASSET RENAME COLUMN VPLANTVAR TO PLANT_VAR;


--TABEL PIC
ALTER TABLE AHMGAWPM.AHMGAWPM_TBLPIC RENAME TO PIC;
ALTER TABLE AHMGAWPM.PIC RENAME COLUMN VNRP TO NRP_ID;
ALTER TABLE AHMGAWPM.PIC RENAME COLUMN VNAMA TO NAMA;
ALTER TABLE AHMGAWPM.PIC RENAME COLUMN VNAMADEPARTEMEN TO DEPARTEMEN;
ALTER TABLE AHMGAWPM.PIC RENAME COLUMN VNAMASEKSI TO SEKSI;
ALTER TABLE AHMGAWPM.PIC RENAME COLUMN VNAMADIVISI TO DIVISI;

--TABEL PLANT
ALTER TABLE AHMGAWPM.AHMGAWPM_TBLPLANT RENAME TO PLANT;
ALTER TABLE AHMGAWPM.PLANT RENAME COLUMN VPLANTVAR TO PLANT_VAR;
ALTER TABLE AHMGAWPM.PLANT RENAME COLUMN VPLANTDESC TO PLANT_DESC;

--TABEL PO
ALTER TABLE AHMGAWPM.AHMGAWPM_TBLPO RENAME TO PURCHASING_ORDER;
ALTER TABLE AHMGAWPM.PURCHASING_ORDER RENAME COLUMN VNOPO TO NO_PO;
ALTER TABLE AHMGAWPM.PURCHASING_ORDER RENAME COLUMN VPODESC TO PO_DESC;
ALTER TABLE AHMGAWPM.PURCHASING_ORDER RENAME COLUMN VSUPPLYID TO SUPPLY_ID;

--TABEL SUPPLIER
ALTER TABLE AHMGAWPM.AHMGAWPM_TBLSUPPLIER RENAME TO SUPPLIER;
ALTER TABLE AHMGAWPM.SUPPLIER RENAME COLUMN VSUPPLYID TO SUPPLY_ID;
ALTER TABLE AHMGAWPM.SUPPLIER RENAME COLUMN VSUPPLDESC TO SUPPLY_DESC;

--TABEL TASK LIST
ALTER TABLE AHMGAWPM.AHMGAWPM_TBLTASKLIST RENAME TO TASK_LIST;
ALTER TABLE AHMGAWPM.TASK_LIST RENAME COLUMN VKODETASKLIST TO KODE_TASK_LIST;
ALTER TABLE AHMGAWPM.TASK_LIST RENAME COLUMN VTITLETASKLIST TO TITLE_TASK_LIST;
ALTER TABLE AHMGAWPM.TASK_LIST RENAME COLUMN VNOASSET TO NO_ASSET;

--TABEL USER
ALTER TABLE AHMGAWPM.AHMGAWPM_TBLUSER RENAME TO "USER";

SELECT SUPPLY_ID, SUPPLY_DESC FROM HEADER_IKP
WHERE (:supplyId IS NULL OR SUPPLY_ID LIKE (CONCAT(CONCAT('%',:supplyId),'%')))
AND (:supplyDesc IS NULL OR SUPPLY_DESC LIKE (CONCAT(CONCAT('%', :supplyDesc), '%')));

SELECT NRP_ID, NAMA FROM PIC WHERE (:nrpId IS NULL OR NRP_ID LIKE (CONCAT(CONCAT('%',:nrpId),'%')))
AND (:nama IS NULL OR NAMA LIKE (CONCAT(CONCAT('%',:nama),'%')));

SELECT  count(*) FROM (SELECT NO_PO, PO_DESC FROM PURCHASING_ORDER WHERE (:noPo IS NULL OR NO_PO LIKE (CONCAT(CONCAT('%',:noPo),'%')))
AND (:poDesc IS NULL OR PO_DESC LIKE (CONCAT(CONCAT('%',:poDesc),'%')))) ;

SELECT PLANT_VAR, PLANT_DESC FROM PLANT WHERE (:plantVar IS NULL OR PLANT_VAR LIKE (CONCAT(CONCAT('%',:plantVar),'%')))
AND (:plantDesc IS NULL OR PLANT_DESC LIKE (CONCAT(CONCAT('%',:plantDesc),'%')));

SELECT NO_ASSET, DESC_ASSET FROM ASSET WHERE (:plantVar = PLANT_VAR)
AND (:noAsset IS NULL OR NO_ASSET LIKE (CONCAT(CONCAT('%',:noAsset),'%')))
AND (:descAsset IS NULL OR DESC_ASSET LIKE (CONCAT(CONCAT('%',:descAsset),'%')));

SELECT KODE_TASK_LIST, TITLE_TASK_LIST FROM TASK_LIST
WHERE (NO_ASSET = :noAsset)
AND (:kode IS NULL OR LOWER(KODE_TASK_LIST) LIKE LOWER(CONCAT(CONCAT('%',:kode),'%')))
AND (:title IS NULL OR LOWER(TITLE_TASK_LIST) LIKE LOWER(CONCAT(CONCAT('%',:title),'%')));

SELECT IKP_ID, PROJECT_DETAIL FROM HEADER_IKP WHERE (:ikpId IS NULL OR LOWER(IKP_ID) LIKE LOWER(CONCAT(CONCAT('%',:ikpId),'%')))
OR (:projectDetail IS NULL OR LOWER(PROJECT_DETAIL) LIKE LOWER(CONCAT(CONCAT('%',:projectDetail),'%')));

SELECT IKP_ID, ASSET_NO, AREA_DETAIL, IN_OUT, CRITICALITY, TASK_LIST FROM AREA_PEKERJAAN 
WHERE IKP_ID = :ikpId;

INSERT INTO "USER"  VALUES ('dararyanti','dararyanti','admin');